-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.brands
(
    _id character varying COLLATE pg_catalog."default" NOT NULL DEFAULT gen_random_uuid(),
    __v integer NOT NULL DEFAULT 1,
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
    "deletedAt" timestamp without time zone,
    "lastSyncAt" timestamp without time zone,
    logo character varying COLLATE pg_catalog."default",
    name jsonb NOT NULL,
    picture character varying COLLATE pg_catalog."default",
    "referTo" character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'tryvnd@point24h.com'::character varying,
    CONSTRAINT "PK_fccd13f3d4cd2a3bb17b0d3c9fb" PRIMARY KEY (_id)
);

CREATE TABLE IF NOT EXISTS public.brands_categories_categories
(
    "brandId" character varying COLLATE pg_catalog."default" NOT NULL,
    "categoryId" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_f2b697ae8c1be818f2d94b992b6" PRIMARY KEY ("brandId", "categoryId")
);

CREATE TABLE IF NOT EXISTS public.brands_suppliers_users
(
    "brandId" character varying COLLATE pg_catalog."default" NOT NULL,
    "supplierId" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_978d1bf044672b58d48b43bbd22" PRIMARY KEY ("brandId", "supplierId")
);

CREATE TABLE IF NOT EXISTS public.categories
(
    _id character varying COLLATE pg_catalog."default" NOT NULL DEFAULT gen_random_uuid(),
    __v integer NOT NULL DEFAULT 1,
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
    "deletedAt" timestamp without time zone,
    "lastSyncAt" timestamp without time zone,
    auto boolean NOT NULL DEFAULT false,
    "categoryPicture" character varying COLLATE pg_catalog."default" NOT NULL,
    name jsonb NOT NULL,
    "referTo" character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'tryvnd@point24h.com'::character varying,
    "sortIndex" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_41b10fde49e2e6b0c771fa2ad5e" PRIMARY KEY (_id)
);

CREATE TABLE IF NOT EXISTS public.categories_brands_brands
(
    "categoryId" character varying COLLATE pg_catalog."default" NOT NULL,
    "brandId" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_bd4654cf46ba7a4846a210e11ec" PRIMARY KEY ("categoryId", "brandId")
);

CREATE TABLE IF NOT EXISTS public.categories_suppliers_users
(
    "categoryId" character varying COLLATE pg_catalog."default" NOT NULL,
    "userId" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_8ea9df5c4d32008f9c6be6d43f3" PRIMARY KEY ("categoryId", "userId")
);

CREATE TABLE IF NOT EXISTS public.contracts
(
    _id character varying COLLATE pg_catalog."default" NOT NULL DEFAULT gen_random_uuid(),
    __v integer NOT NULL DEFAULT 1,
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
    "deletedAt" timestamp without time zone,
    "lastSyncAt" timestamp without time zone,
    "startDate" date NOT NULL,
    "endDate" date NOT NULL,
    description character varying COLLATE pg_catalog."default" NOT NULL,
    status contracts_status_enum NOT NULL DEFAULT 'active'::contracts_status_enum,
    "feePerSale" numeric NOT NULL,
    "feeType" contracts_feetype_enum NOT NULL,
    supplier_id character varying COLLATE pg_catalog."default",
    "totalSales" numeric NOT NULL,
    "totalRevenue" numeric NOT NULL,
    orders_id character varying COLLATE pg_catalog."default",
    CONSTRAINT "PK_24bd7f628751c5ae03d5463466d" PRIMARY KEY (_id)
);

CREATE TABLE IF NOT EXISTS public.order_details
(
    _id character varying COLLATE pg_catalog."default" NOT NULL DEFAULT gen_random_uuid(),
    __v integer NOT NULL DEFAULT 1,
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
    "deletedAt" timestamp without time zone,
    "lastSyncAt" timestamp without time zone,
    quantity integer NOT NULL,
    discount numeric NOT NULL,
    proposed boolean NOT NULL,
    lane character varying COLLATE pg_catalog."default" NOT NULL,
    row_number character varying COLLATE pg_catalog."default" NOT NULL,
    snapshot_name character varying COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    "soldPrice" numeric NOT NULL,
    tax_amount numeric NOT NULL,
    retail_price numeric NOT NULL,
    order_id character varying COLLATE pg_catalog."default",
    product_id character varying COLLATE pg_catalog."default",
    supplier_id character varying COLLATE pg_catalog."default",
    category_id character varying COLLATE pg_catalog."default",
    brand_id character varying COLLATE pg_catalog."default",
    CONSTRAINT "PK_27ef2f16ca4941451b3d40c032d" PRIMARY KEY (_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    _id character varying COLLATE pg_catalog."default" NOT NULL DEFAULT gen_random_uuid(),
    __v integer NOT NULL DEFAULT 1,
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
    "deletedAt" timestamp without time zone,
    "lastSyncAt" timestamp without time zone,
    status character varying COLLATE pg_catalog."default" NOT NULL,
    payment_type character varying COLLATE pg_catalog."default" NOT NULL,
    lang character varying COLLATE pg_catalog."default" NOT NULL,
    "referTo" character varying COLLATE pg_catalog."default" NOT NULL,
    tax numeric NOT NULL,
    total numeric NOT NULL,
    currency character varying COLLATE pg_catalog."default" NOT NULL,
    "createdAtUtc" timestamp without time zone NOT NULL,
    "utcOffset" numeric NOT NULL,
    payment_transaction_id character varying COLLATE pg_catalog."default" NOT NULL,
    payment_receipt character varying COLLATE pg_catalog."default" NOT NULL,
    cart_number character varying COLLATE pg_catalog."default" NOT NULL,
    card_number character varying COLLATE pg_catalog."default" NOT NULL,
    card_department character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    reservation_code character varying COLLATE pg_catalog."default" NOT NULL,
    return_code character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_252c2a9858ce5be707f5c84e78a" PRIMARY KEY (_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    _id character varying COLLATE pg_catalog."default" NOT NULL DEFAULT gen_random_uuid(),
    __v integer NOT NULL DEFAULT 1,
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
    "deletedAt" timestamp without time zone,
    "lastSyncAt" timestamp without time zone,
    upc character varying COLLATE pg_catalog."default",
    "additionPrice" numeric NOT NULL DEFAULT '0'::numeric,
    "ageControl" integer NOT NULL DEFAULT 0,
    name jsonb NOT NULL,
    barcode character varying COLLATE pg_catalog."default",
    "costPrice" numeric NOT NULL,
    description jsonb,
    detail jsonb,
    include jsonb,
    ingredients jsonb,
    "keyFeatures" jsonb,
    specification jsonb,
    dimension jsonb,
    price numeric NOT NULL,
    "pricePerKilo" boolean NOT NULL,
    "prodType" character varying COLLATE pg_catalog."default",
    "productPictures" text COLLATE pg_catalog."default" NOT NULL,
    "productVideo" character varying COLLATE pg_catalog."default",
    "referTo" character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'tryvnd@point24h.com'::character varying,
    "sortIndex" integer NOT NULL DEFAULT 0,
    "vatIndex" integer NOT NULL DEFAULT 0,
    "virtualProduct" integer NOT NULL DEFAULT 0,
    supplier_id character varying COLLATE pg_catalog."default",
    brand_id character varying COLLATE pg_catalog."default",
    category_id character varying COLLATE pg_catalog."default",
    quantity integer NOT NULL DEFAULT 0,
    stock integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_bb9432d5569253ad39cd0061760" PRIMARY KEY (_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    _id character varying COLLATE pg_catalog."default" NOT NULL DEFAULT gen_random_uuid(),
    __v integer NOT NULL DEFAULT 1,
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
    "deletedAt" timestamp without time zone,
    "lastSyncAt" timestamp without time zone,
    "firstName" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "lastName" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    "businessName" character varying(32) COLLATE pg_catalog."default",
    password character varying COLLATE pg_catalog."default" NOT NULL,
    role users_role_enum NOT NULL DEFAULT 'supplier'::users_role_enum,
    "phoneNumber" character varying COLLATE pg_catalog."default" NOT NULL,
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT "PK_46c438e5a956fb9c3e86e73e321" PRIMARY KEY (_id),
    CONSTRAINT "UQ_1e3d0240b49c40521aaeb953293" UNIQUE ("phoneNumber"),
    CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE (email)
);

ALTER TABLE IF EXISTS public.brands_categories_categories
    ADD CONSTRAINT "FK_e6d269d7c7eff912d6c479416ac" FOREIGN KEY ("brandId")
    REFERENCES public.brands (_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IDX_e6d269d7c7eff912d6c479416a"
    ON public.brands_categories_categories("brandId");


ALTER TABLE IF EXISTS public.brands_categories_categories
    ADD CONSTRAINT "FK_f1385bec1e0009516ce48e1f158" FOREIGN KEY ("categoryId")
    REFERENCES public.categories (_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IDX_f1385bec1e0009516ce48e1f15"
    ON public.brands_categories_categories("categoryId");


ALTER TABLE IF EXISTS public.brands_suppliers_users
    ADD CONSTRAINT "FK_1921c070179ec1fea6661134119" FOREIGN KEY ("brandId")
    REFERENCES public.brands (_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IDX_1921c070179ec1fea666113411"
    ON public.brands_suppliers_users("brandId");


ALTER TABLE IF EXISTS public.brands_suppliers_users
    ADD CONSTRAINT "FK_3d205b38f46ed3cb1e20e4d7f6a" FOREIGN KEY ("supplierId")
    REFERENCES public.users (_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IDX_3d205b38f46ed3cb1e20e4d7f6"
    ON public.brands_suppliers_users("supplierId");


ALTER TABLE IF EXISTS public.categories_brands_brands
    ADD CONSTRAINT "FK_37d4aca975ceb75c6dedb15792e" FOREIGN KEY ("categoryId")
    REFERENCES public.categories (_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IDX_37d4aca975ceb75c6dedb15792"
    ON public.categories_brands_brands("categoryId");


ALTER TABLE IF EXISTS public.categories_brands_brands
    ADD CONSTRAINT "FK_a85fc325c51ad1700dfde811dbc" FOREIGN KEY ("brandId")
    REFERENCES public.brands (_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IDX_a85fc325c51ad1700dfde811db"
    ON public.categories_brands_brands("brandId");


ALTER TABLE IF EXISTS public.categories_suppliers_users
    ADD CONSTRAINT "FK_a3687ddb4de7fdf099e6fc9d736" FOREIGN KEY ("categoryId")
    REFERENCES public.categories (_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IDX_a3687ddb4de7fdf099e6fc9d73"
    ON public.categories_suppliers_users("categoryId");


ALTER TABLE IF EXISTS public.categories_suppliers_users
    ADD CONSTRAINT "FK_a8f14a82b616c308c5799c60332" FOREIGN KEY ("userId")
    REFERENCES public.users (_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IDX_a8f14a82b616c308c5799c6033"
    ON public.categories_suppliers_users("userId");


ALTER TABLE IF EXISTS public.contracts
    ADD CONSTRAINT "FK_81870b86ad871f22c3980f6174c" FOREIGN KEY (supplier_id)
    REFERENCES public.users (_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_details
    ADD CONSTRAINT "FK_3ff3367344edec5de2355a562ee" FOREIGN KEY (order_id)
    REFERENCES public.orders (_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.order_details
    ADD CONSTRAINT "FK_6504c11ff0d81a959a66f46e5bc" FOREIGN KEY (category_id)
    REFERENCES public.categories (_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_details
    ADD CONSTRAINT "FK_827fd3f8edc374da4981148645b" FOREIGN KEY (supplier_id)
    REFERENCES public.users (_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_details
    ADD CONSTRAINT "FK_c60eff3bd1046a5413882c8a89f" FOREIGN KEY (brand_id)
    REFERENCES public.brands (_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_details
    ADD CONSTRAINT "FK_ce1f689e43b39edd9330cadaeb8" FOREIGN KEY (product_id)
    REFERENCES public.products (_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT "FK_0ec433c1e1d444962d592d86c86" FOREIGN KEY (supplier_id)
    REFERENCES public.users (_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT "FK_1530a6f15d3c79d1b70be98f2be" FOREIGN KEY (brand_id)
    REFERENCES public.brands (_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY (category_id)
    REFERENCES public.categories (_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;
