name: Backend CI

on:
  push:
    branches:
      - 'main'

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    outputs:
      node-modules-path: ${{ steps.install.outputs.node-modules-path }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        id: install
        run: pnpm install
        continue-on-error: true

      - name: Cache node_modules
        if: steps.install.outcome == 'success'
        uses: actions/cache@v2
        with:
          path: ${{ steps.install.outputs.node-modules-path }}
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

  evaluate-affected-projects:
    runs-on: ubuntu-latest
    needs: cache-and-install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore cached node_modules
        uses: actions/cache@v2
        with:
          path: ${{ needs.cache-and-install.outputs.node-modules-path }}
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Check for Affected Projects
        uses: dkhunt27/action-nx-affected-list@v5
        id: checkForAffected


  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Affected Projects
        uses: dkhunt27/action-nx-affected-list@v5
        id: checkForAffected

#      - if: steps.checkForAffected.outputs.hasAffected == 'true'
#        name: Build (Nx Affected)
#        uses: mansagroup/nrwl-nx-action@v2
#        with:
#          targets: build
#          affected: true
#          nxCloud: false
#
#      - name: Notify Slack
#        run: |
#          curl -X POST -H 'Content-type: application/json' --data \
#          '{"channel": "#kingo", "username": "5oStudios", "text": "New Build Starts!, project: `game`", "icon_emoji": ":5ostudios:"}' \
#            ${{ secrets.SLACK_WEBHOOK }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        id: setup_qemu

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: setup_buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        id: login_to_docker_hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          file: apps/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/vnd-dev-backend:latest

#      - name: Notify Slack
#        run: |
#          curl -X POST -H 'Content-type: application/json' --data \
#          '{"channel": "#kingo", "username": "5oStudios", "text": "Build Success!, project `game`", "icon_emoji": ":5ostudios:"}' \
#            ${{ secrets.SLACK_WEBHOOK }}
#
#      - name: Deploy to Staging
#        run: |
#          curl -X GET \
#            -H "Authorization: Bearer ${{ secrets.COOLIFY_KEY_FRONTEND_STAGING }}" \
#              ${{ secrets.COOLIFY_WEBHOOK_FRONTEND_STAGING }}
