name: Backend CI

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test Affected Projects
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm@8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format code
        run: pnpm format

      - name: Lint code
        run: pnpm lint

      - name: Test code
        run: pnpm test

      - name: Evaluate Affected Projects
        id: checkForAffected
        run: pnpm run nx affected:apps --plain

      - name: Build and Test Affected Projects
        if: steps.checkForAffected.outputs.stdout != ''
        run: pnpm run nx affected:build --base=main --prod

      - name: Upload node_modules
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: ./node_modules

  build-docker-image:
    runs-on: ubuntu-latest
    needs: build-and-test
    name: Build Docker Image for Affected Projects
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download node_modules
        uses: actions/download-artifact@v2
        with:
          name: node_modules
          path: ./node_modules

      - name: Build Docker Image
        run: docker build -t your-docker-username/your-image-name:latest .

      - name: Push Docker Image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/test
