#name: Docker
#on:
#  - pull_request
#  - push
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      -
#        name: Checkout
#        uses: actions/checkout@v4
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      -
#        name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: ./Dockerfile
#          tags: monorepo:latest
#          outputs: type=docker,dest=/tmp/monorepo.tar
#      -
#        name: Upload artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: monorepo
#          path: /tmp/monorepo.tar
#
#  use:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      -
#        name: Download artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: monorepo
#          path: /tmp
#      -
#        name: Load Docker image
#        run: |
#          docker load --input /tmp/monorepo.tar
#          docker image ls -a
