name: Linting and Formatting

on:
    pull_request:
        branches:
        - staging


jobs:
  install-and-cache:
    runs-on: ubuntu-latest
    name: Install and Cache Dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8.15.8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - uses: nrwl/nx-set-shas@v4

      - run: |
          git fetch origin
          if ! git show-ref --quiet refs/remotes/origin/main; then
            git branch --track main origin/main
          else
            echo "Branch 'main' already exists. Skipping branch creation."
          fi

      - run: pnpm i nx -g

      - run: nx affected:lint --fix --parallel
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: lint fix"

      - run: nx affected -t format:write --parallel
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: format write"
