name: PR Review
on: pull_request
permissions:
    contents: read
    pull-requests: write

jobs:
  tsc:
    name: runner / tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EPMatt/reviewdog-action-tsc@v1
        with:
          github_token: ${{ secrets.REALEASE_PLEASE_PAT }}
          reporter: github-pr-review
          level: warning
